#! /usr/bin/env bash

set -euo pipefail

config_name="xarray_cunet_continuous"
dataset="bham_gcmx-4x_spechum-temp-vort_random"

workdir="output/test/${config_name}"
config_path="configs/subvp/${config_name}.py"

map_features=1
train_batch_size=2

rm -rf ${workdir}
WANDB_EXPERIMENT_NAME="test" python main.py --workdir ${workdir} --config ${config_path} --mode train --config.data.dataset_name=${dataset} --config.training.snapshot_freq=5 --config.training.eval_freq=100 --config.training.log_freq=50 --config.training.n_epochs=2 --config.model.map_features=${map_features} --config.training.batch_size=${train_batch_size} --config.data.input_transform_key=stanurrecen --config.data.target_transform_key=sqrturrecen

epoch=2
num_samples=2
eval_batchsize=32

rm -rf "${workdir}/samples/epoch-${epoch}/${dataset}"
python predict.py ${workdir} --dataset ${dataset} --epoch ${epoch} --batch-size ${eval_batchsize} --num-samples ${num_samples}
