#! /usr/bin/env bash

set -euo pipefail

config_name="xarray_cunet_continuous"
dataset="bham_gcmx-4x_spechum-temp-vort_random"

workdir="output/test/${config_name}"
config_path="configs/subvp/${config_name}.py"

map_features=1
train_batch_size=2

rm -rf ${workdir}
python main.py --workdir ${workdir} --config ${config_path} --mode train --config.data.dataset_name=${dataset} --config.training.snapshot_freq=5 --config.training.eval_freq=2 --config.training.log_freq=1 --config.training.n_iters=15 --config.model.map_features=${map_features} --config.training.batch_size=${train_batch_size}

checkpoint=2
num_samples=2
eval_batchsize=128

rm -rf "${workdir}/samples/checkpoint-${checkpoint}/${dataset}"
python predict.py ${workdir} --dataset ${dataset} --checkpoint-id ${checkpoint} --batch-size ${eval_batchsize} --num-samples ${num_samples}
